version: '3.8'

services:
  db-symf-online-learning:
    image: mysql:5.7
    volumes:
      - db-symf-online-learning-data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db-symf-online-learning
      MYSQL_PASSWORD: password
    networks:
      - db-symf-online-learning-net

  db-symf-online-learning-phpmyadmin:
    depends_on:
      - db-symf-online-learning
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db-symf-online-learning
      MYSQL_ROOT_PASSWORD: password
    networks:
      - db-symf-online-learning-net

networks:
  db-symf-online-learning-net:

volumes:
  db-symf-online-learning-data:
